### ISSUE TITLE
Create script

### ISSUE THREAD

**Issue by theodorosploumis** [BoxUpp/boxupp#1]
I am trying to create a script but in the **Script Source** I always get errors. Documentation is still to be created and I decided to ask for help here. So,
- What kind of script can I use?
- Is it a bash script or something else?
- The "Script Name" is also the file name?

![boxupp](https://cloud.githubusercontent.com/assets/1315321/6059938/2583a68c-ad40-11e4-95f2-68f1a103b073.png)

**Comment by akskap** [comment]
Seems to be a ace-editor misconfiguration. Javascript mode has been used, but this particular screen should have a Shell mode to back the validations.

However, this issue should not alter the functionality in any case. Script is still written down on the disk as it is.

You can use bash scripts here and, yes, the script name is the file name here.

**Comment by BoxUpp** [comment]
@theodorosploumis Issue resolved and code committed to the repository

Thank you !
